import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import SessionProvider from "../context/sessionProvider"; // Importe o novo componente Providers
import { getServerSession } from "next-auth"; // Importe getServerSession

// Importe as configurações de autenticação (se estiverem em um arquivo separado)
// Exemplo: import { authOptions } from "@/app/api/auth/[...nextauth]/route";
// Certifique-se de que o caminho está correto para o seu projeto

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Obtenha a sessão no lado do servidor
  // Certifique-se de ter suas 'authOptions' configuradas corretamente
  // importadas de onde você as definiu (geralmente em api/auth/[...nextauth]/route.ts)
  const session = await getServerSession(/* authOptions */); // Passar suas authOptions aqui se necessário

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionProvider session={session}>
          <Header />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}